### ISSUE TITLE
make note that server url must end in `/rsc`

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/connectapi#71]

**Comment by colearendt** [comment]
Worth noting that this is only a Colorado thing (because we host all 3 products at colorado.rstudio.com, they must be delimited by a trailing path). Unfortunately, there is not a great solution to this on the `connectapi` side, because there is no way for us to determine (1) whether a path is necessary and (2) if it is, what would it be. I.e. we could host connect at `/party` or `/presto` or any manner of other path 😄 

Perhaps some way to back into the proper Connect URL would be handy, but I do not have a good sense for how to do that at present. I am going to close this for now, although ideas are welcome!
