### ISSUE TITLE
The audit_vanity_urls function can return wrong urls

### ISSUE THREAD

**Issue by mac-pfa** [rstudio/connectapi#9]
If the "server" option is defined without a "http://" prefix (which is not needed for the connect or cache_apps functions) the vanity urls are returned as "http:///my_vanity_url/" which seems wrong.
With the prefix they are returned correctly as "/my_vanity_url/".

**Comment by colearendt** [comment]
#111 will resolve this. Unfortunately `httr::parse_url()` cannot handle the case where there is no protocol defined, and the way this is implemented today, we don't have a whole lot of choices. As a result, I have cleaned up some of the edge cases to:
- make sure slashes are consistent
- error if protocol is missing
- simplify the url replacement to only care about server prefix path (i.e. hosting Connect at `/rstudio/` or something like that)

Ultimately my hope is that we will implement this better long term (or the product will do a better job of returning vanity URLs as components rather than complete URLs)

**Comment by colearendt** [comment]
If https://github.com/r-lib/httr/issues/689 is ever closed, we could potentially revisit this behavior and take a corresponding version constraint on `httr`
