### ISSUE TITLE
Plan for future CRAN publication?

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/connectapi#92]
Is there a plan for a CRAN published version of the {connectapi} package? For many airgapped RStudio Connect users they cannot use the {connectapi} package unless the package is built manually for their RSPM instance. 

Having this package published to CRAN would add a lot of comfort around using the API today.

A few foreseeable challenges: 

- Is the package up to date with the newest release? 
- Conflation of this package with our existing SLA

**Comment by jthomasmock** [comment]
Also ran into this, many of the Enterprise customers cannot install or rely on GitHub-only packages. It would be ideal to be able to relay them to `connectapi` as a CRAN package.

**Comment by jthomasmock** [comment]
I agree w/ Josiah that gracefully handling API versioning based on available endpoints for older RSC installs is warranted.

**Comment by colearendt** [comment]
Thanks for the issue to track this! We definitely do want to get this on CRAN. Our hold up at present has definitely been related to the conflation of the package with SLA, version compatibility issues, release timelines, and Connect API conventions (i.e. whether an endpoint is public and reliable or not).

I definitely think it is important that we prioritize this, since the package has received so much adoption, though!

**Comment by colearendt** [comment]
Started a project to track here: https://github.com/rstudio/connectapi/projects/1

**Comment by Vonderful** [comment]
Is there any update on this please? I am unable to use the standard install method due to business platform lockdowns, and am yet to find a way to install when i know this package would be of great use!
