### ISSUE TITLE
set_vanity_url(content, NULL) does not remove vanity URL

### ISSUE THREAD

**Issue by jlfsjunior** [rstudio/connectapi#96]
Hi there,

I just noticed that `set_vanity_url(content, NULL)` does not remove the vanity url. Is it the intended behaviour?

As a side note, `set_run_as(content, NULL)` does work and resets to the default user.

I am using `connectapi_0.1.0.9018`, just installed from master.

Thanks!

**Comment by colearendt** [comment]
Thanks for the report here! Apologies for the issue! I haven't dug into this yet, but I suspect this is because the API expects us to do a `DELETE` instead of a `PUT null`. 

The other possibility could be that it expects `set_vanity_url(content, NA)`? Do you mind giving that a try and see if it works?

**Comment by colearendt** [comment]
I confirmed that this does not work today. Does `set_vanity_url(content, NULL)` or `unset_vanity_url(content)` make more sense?

**Comment by jlfsjunior** [comment]
@colearendt, sorry for not replying, I was crazy busy and now I'm out of office... Thanks for confirming that it doesn't work! 😄 

I like `delete_vanity_url` better if the API has a DELETE endpoint (quite sure the question wasn't to me though...).

**Comment by colearendt** [comment]
Thanks for the reply!! I like `delete_vanity_url()` too. (And the question definitely was to you 😄). I'll take a look at implementing!

Have a great time out of office! Rest is important!
